version: "3.9"
services:
  redis-server:
    image: "redis:alpine"
    # container_name: "redis-app"
    ports:
      - "6379:6379"
    networks:
      - backend
  web-server: 
    # container_name: "web-app"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    volumes:
      #  Named volumes
      - webAppVolume:/var/www/html/app/public/
    # depends_on:
      # - redis-server 
    networks:
      - backend
    environment:
      - appName=nodeDockerApp
networks:
  # frontend:
  backend:
volumes:
  webAppVolume: